name: Child Workflow

on:
  workflow_dispatch:
    inputs:
      fruits:
        description: 'JSON array of fruits'
        required: true

jobs:
  process_fruit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: ${{ fromJson(github.event.inputs.fruits) }}
      fail-fast: false
    steps:
      - name: Check Fruit
        run: echo "Checking ${{ matrix.fruit }}"

      - name: Wash Fruit
        if: matrix.fruit != 'durian'
        run: echo "Washing ${{ matrix.fruit }}"

      - name: Peel Fruit
        if: matrix.fruit == 'banana' || matrix.fruit == 'durian'
        run: echo "Peeling ${{ matrix.fruit }}"

      - name: Slice Fruit
        if: matrix.fruit == 'apple' || matrix.fruit == 'cherry'
        run: echo "Slicing ${{ matrix.fruit }}"
