name: Child Workflow

on:
  workflow_dispatch:
    inputs:
      fruits:
        description: 'JSON array of fruits'
        required: true

jobs:
  process_fruit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: ${{ fromJson(github.event.inputs.fruits) }}
      fail-fast: false
    steps:
      - name: Process Fruit
        run: |
          echo "Processing ${{ matrix.fruit }}"
          # Simulating a failure condition for one of the fruits
          if [ "${{ matrix.fruit }}" == "durian" ]; then
            exit 1
          fi
