name: Main Workflow

on:
  push:
    branches:
        master
  pull_request:
  workflow_dispatch:
    inputs:
      fruits:
        description: 'Specify fruits'
        required: true

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello from first job!"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    strategy:
      fail-fast: false
    steps:
      - name: Run Child Build Workflow
        uses: ./.github/workflows/child-workflow.yml
        with:
          fruits: ${{ github.event.inputs.fruits }}
      - name: Continue Main Workflow
        run: echo "Continuing with the main workflow"
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello from third job!"
