name: Main Workflow

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First Job Action
        run: echo "Executing First Job"

  trigger_child_workflow:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Trigger Child Workflow
        uses: actions/github-script@v4
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'child-workflow.yaml',
              ref: 'master',
              inputs: {
                'fruits': '["apple", "banana", "cherry", "durian"]'
              }
            })

  job3:
    runs-on: ubuntu-latest
    needs: trigger_child_workflow
    steps:
      - name: Third Job Action
        run: echo "Executing Third Job"
